trigger: none

resources:
  pipelines:
    - pipeline: build-artifact
      project: Remindr
      source: Build
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'windows-latest'

variables:
  - template: variables/global.yml
  - template: variables/dev.yml
  - group: Dev

stages:
  - stage: SetBuildName
    displayName: 'Set build name'
    jobs:
      - template: jobs/setBuildName.yml

  - stage: Infrastructure
    jobs:
      - template: jobs/bicep.yml

  - stage: DeployCode
    displayName: 'Deploy code'
    jobs:
      - template: jobs/appService.yml
      - template: jobs/dbUp.yml
